# Generated by Django 5.0.3 on 2024-03-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
