# Generated by Django 5.0.3 on 2024-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofil_nb_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('player1', models.IntegerField()),
                ('player2', models.IntegerField(blank=True, null=True)),
                ('pseudo_p1', models.CharField(default='', max_length=32)),
                ('pseudo_p2', models.CharField(default='', max_length=32)),
                ('winner', models.CharField(default='', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
