# Generated by Django 5.0.4 on 2024-04-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tournamentsgame_game_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='score1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
